name: 'go-version'
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  go-version:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - name: 'compare Go versions'
        env:
          GH_TOKEN: ${{ github.token }}
        run: nix run .#goVersion
